server:
  port: 8081

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  profiles:
    active: prod
  config:
    import: optional:configserver:http://localhost:8888